# Generated by Django 2.0.13 on 2019-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['entry_date', 'ordinal']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='ordinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='sequence in day'),
        ),
    ]
