# Generated by Django 2.0.13 on 2019-11-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20191120_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='is_fippable',
            new_name='is_flippable',
        ),
    ]
