# Generated by Django 2.0.13 on 2019-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20191120_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='interpret_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='interpret_more',
            field=models.TextField(blank=True, default=''),
        ),
    ]
