# Generated by Django 2.0.13 on 2020-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20191213_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(blank=True, default='', verbose_name='Transcription'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='interpret_blurb',
            field=models.TextField(blank=True, default='', verbose_name='Interpretation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='interpret_more',
            field=models.TextField(blank=True, default='', verbose_name='Drawing Interpretation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Sequence on Trail'),
        ),
    ]
